/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FirstVisitRouteImport } from './routes/first-visit'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as IntakeTokenRouteImport } from './routes/intake.$token'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google-calendar-callback'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstVisitRoute = FirstVisitRouteImport.update({
  id: '/first-visit',
  path: '/first-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakeTokenRoute = IntakeTokenRouteImport.update({
  id: '/intake/$token',
  path: '/intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar-callback',
    path: '/api/public/google-calendar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/first-visit': typeof FirstVisitRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/api/public/google-calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/first-visit': typeof FirstVisitRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes': typeof NotesIndexRoute
  '/api/public/google-calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/first-visit': typeof FirstVisitRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/api/public/google-calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/first-visit'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/intake/$token'
    | '/notes/$slug'
    | '/notes/'
    | '/api/public/google-calendar-callback'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/first-visit'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/intake/$token'
    | '/notes/$slug'
    | '/notes'
    | '/api/public/google-calendar-callback'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/first-visit'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/intake/$token'
    | '/notes/$slug'
    | '/notes/'
    | '/api/public/google-calendar-callback'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FirstVisitRoute: typeof FirstVisitRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  IntakeTokenRoute: typeof IntakeTokenRoute
  NotesSlugRoute: typeof NotesSlugRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-visit': {
      id: '/first-visit'
      path: '/first-visit'
      fullPath: '/first-visit'
      preLoaderRoute: typeof FirstVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$token': {
      id: '/intake/$token'
      path: '/intake/$token'
      fullPath: '/intake/$token'
      preLoaderRoute: typeof IntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar-callback': {
      id: '/api/public/google-calendar-callback'
      path: '/api/public/google-calendar-callback'
      fullPath: '/api/public/google-calendar-callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FirstVisitRoute: FirstVisitRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  IntakeTokenRoute: IntakeTokenRoute,
  NotesSlugRoute: NotesSlugRoute,
  NotesIndexRoute: NotesIndexRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
